services:
  db1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: webProjekat
    ports:
      - "1444:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=LozinkaJakaWebProjekatSifra!#
